### ISSUE TITLE
react生命周期函数书写错误

### ISSUE THREAD

**Issue by zvzuola** [KieSun/InterviewMap#26]
https://yuchengkai.cn/docs/zh/frontend/react.html#v16-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E5%87%BD%E6%95%B0%E7%94%A8%E6%B3%95%E5%BB%BA%E8%AE%AE
// 组件销毁后调用
componentDidMount() {}
此处生命周期函数写错了

**Comment by KieSun** [comment]
好的 感谢，下次可以提个 PR
