### ISSUE TITLE
类型转换这里有纰漏

### ISSUE THREAD

**Issue by Volankey** [KieSun/InterviewMap#39]
[](https://yuchengkai.cn/docs/zh/frontend/#转boolean)

<img width="699" alt="image" src="https://user-images.githubusercontent.com/23287363/42793382-84767592-89ac-11e8-99ad-aa4136483f04.png">
这种情况
<img width="98" alt="image" src="https://user-images.githubusercontent.com/23287363/42793418-a7616a3a-89ac-11e8-99a3-96fa5d11bde3.png">
建议这里修改一下

**Comment by KieSun** [comment]
```js
if ([]) {console.log(1)} // => 1
if ([0]) {console.log(1)} // => 1
```

**Comment by KieSun** [comment]
但是你说的也没错，这种情况确实有问题，我考虑下怎么改，因为下面有写到 `==`

**Comment by KieSun** [comment]
前面加了一句话，在条件判断时。
