### ISSUE TITLE
Bug fix in framework.md

### ISSUE THREAD

**Issue by Jemair** [KieSun/InterviewMap#41]
here is a bug in `framework.md`. due to vue-press will auto compress vue interpolation, thus `{{name}}` has been convert to ` `.  I have made a pr. pls take a look. thanks.
![qq20180717-110527](https://user-images.githubusercontent.com/20502467/42794503-b4076870-89b1-11e8-91cb-f77791aa5430.png)

**Comment by KieSun** [comment]
Thanks for your pr.
